id: I7653422A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:52:22+00:00'
last_modified: '2022-06-07T18:28:45.689678+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5291
  title: ཆོས་སྤྱོད་བྱང་ཆེན་སྤྱོད་པའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9C2A:
      image_group_id: I3CN5293
      title: ''
      total_pages: 59
      order: 1
      base_file: 9C2A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
