id: P003221
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5291
  title: ཆོས་སྤྱོད་བྱང་ཆེན་སྤྱོད་པའི་སྒྲོན་མེ།
  author: ''
  volumes:
    fc8fb1f3ef274a2f8f4f8908aaff772c:
      image_group_id: I3CN5293
      title: ''
      volume_number: 1
      total_pages: 59
