id: P003221
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:48:25.100684
source_metadata:
  id: bdr:W3CN5291
  title: ཆོས་སྤྱོད་བྱང་ཆེན་སྤྱོད་པའི་སྒྲོན་མེ།
  author: ''
  volumes:
    fc8fb1f3ef274a2f8f4f8908aaff772c:
      image_group_id: I3CN5293
      title: ''
      volume_number: 1
      total_pages: 59
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
